version = "0.1.0"
name = "deplo-prfilter"
author = { name = "Takehiro Iyatomi", email = "iyatomi@gmail.com" }
entrypoints = {
    workflow = {
        linux = ["bash", "./entrypoint.sh"]
        macos = ["bash", "./entrypoint.sh"]
    }
}
